// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhpqnbJE9uDK7ZZftU8oze1f1zyM7cRE',
    appId: '1:638311798523:android:852f20f1c3c3ea483a825e',
    messagingSenderId: '638311798523',
    projectId: 'tuncmoments-c89ad',
    storageBucket: 'tuncmoments-c89ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPmU36Nz43ciHXWy3mRdsGcD-jzhNUA60',
    appId: '1:638311798523:ios:3629d7637e3e51da3a825e',
    messagingSenderId: '638311798523',
    projectId: 'tuncmoments-c89ad',
    storageBucket: 'tuncmoments-c89ad.appspot.com',
    androidClientId: '638311798523-clghbhktgec13j8rf9jdhmiipr3s0f25.apps.googleusercontent.com',
    iosClientId: '638311798523-4s5lgvj1ktmgq3fsefcnngskj01qt153.apps.googleusercontent.com',
    iosBundleId: 'site.tunckankilic.tuncmoments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPmU36Nz43ciHXWy3mRdsGcD-jzhNUA60',
    appId: '1:638311798523:ios:a9ac0fc392ad51553a825e',
    messagingSenderId: '638311798523',
    projectId: 'tuncmoments-c89ad',
    storageBucket: 'tuncmoments-c89ad.appspot.com',
    androidClientId: '638311798523-clghbhktgec13j8rf9jdhmiipr3s0f25.apps.googleusercontent.com',
    iosClientId: '638311798523-0p9etn5li73doo5869i7kfb1en4i077j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

}